### ISSUE TITLE
[FEATURE] cleanup script - modify docroot

### ISSUE THREAD

**Issue by AndreasA** [Trenker/vagrant-export#4] opened 2015-07-10 06:56 UTC
Modifying the docroot for cleanup script would be a good option.
e.g. if a host is not directly in the main folder but in a subfolder, it would be good to be able to modify it.

**Comment by garfieldius** [comment] 2015-07-15 11:36
Duplicate of #3

**Closed as completed by garfieldius** 2015-07-15 11:36 UTC
Labels: duplicate
