### ISSUE TITLE
[FEATURE] cleanup script - make cleanup of indexed search tables optional

### ISSUE THREAD

**Issue by AndreasA** [Trenker/vagrant-export#5] opened 2015-07-10 06:58 UTC
Cleaning up indexed search table would be nice if it was optional.
After all in order to test index search (e.g. templates), it would be good to have already indexed content.

**Comment by garfieldius** [comment] 2015-07-15 11:36
Duplicate of #3

**Closed as completed by garfieldius** 2015-07-15 11:36 UTC
Labels: duplicate
